import type { Itinerary } from '../types';
import { getStaticImageUrl } from './image-urls';

/**
 * Tours extracted from findyourmorocco.com
 * These are the premium Morocco tour packages
 */
export const FINDYOURMOROCCO_TOURS: Itinerary[] = [
  {
    id: "6-days-tangier-sahara-marrakech",
    order: 1,
    title: "6 Days Sahara Desert Tour",
    subtitle: "Tangier to Marrakech - 2 Nights in the Desert",
    duration: "6 Days",
    difficulty: "Moderate",
    difficultyStars: 3,
    tags: ["Sahara", "Desert", "Cultural", "Adventure"],
    cities: ["Tangier", "Chefchaouen", "Fes", "Merzouga", "Marrakech"],
    description: "Experience Morocco's iconic north-to-south journey with an extended stay in the magical Sahara Desert. Begin in Tangier, cross the forested Rif Mountains, explore the blue-painted town of Chefchaouen, dive into history at Volubilis and Meknes, and explore the spiritual heart of Morocco in Fes. Then turn south through the Middle Atlas Mountains and cedar forests to the edge of the Erg Chebbi dunes.",
    highlights: [
      "Chefchaouen's iconic blue streets",
      "Roman ruins at Volubilis",
      "Imperial city of Fes",
      "Two nights in luxury desert camp",
      "Camel trek in Erg Chebbi dunes",
      "Berber music and culture",
      "Todra Gorge exploration",
      "UNESCO Ait Ben Haddou village",
      "High Atlas Mountains crossing"
    ],
    thumbnail: {
      src: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&h=600&fit=crop",
      alt: "Golden Sahara Desert dunes at sunset",
      position: "object-center"
    },
    dayByDay: [
      { day: 1, title: "Tangier – Rif Mountains – Chefchaouen", description: "Arrive in Tangier, travel through Rif Mountains to the blue-painted town of Chefchaouen. Explore the medina and relax in this mountain paradise." },
      { day: 2, title: "Chefchaouen – Volubilis – Meknes – Fes", description: "Visit Roman archaeological site at Volubilis, explore imperial city of Meknes, arrive in Fes. Evening in the historic medina." },
      { day: 3, title: "Fes – Cedar Forests – Merzouga Desert", description: "Drive south through Middle Atlas Mountains and cedar forests. Arrive in Merzouga for sunset camel trek into Erg Chebbi dunes. Night in luxury desert camp." },
      { day: 4, title: "Sahara Exploration – Desert Camp", description: "Sunrise over dunes. Explore Khamlia village, visit nomadic Berber families, optional sandboarding. Second night in desert guesthouse." },
      { day: 5, title: "Merzouga – Todra Gorge – Skoura – Ait Ben Haddou", description: "Journey through desert plains, explore towering Todra Gorge, pass through palm groves of Skoura Oasis, arrive at UNESCO-listed Ait Ben Haddou." },
      { day: 6, title: "Ait Ben Haddou – High Atlas – Marrakech", description: "Guided tour of fortified village, cross High Atlas Mountains via Tizi n'Tichka Pass, arrive in vibrant Marrakech." },
    ],
  },
  {
    id: "5-days-tangier-sahara",
    order: 2,
    title: "5 Days Morocco Tour from Tangier",
    subtitle: "Chefchaouen, Fes & Sahara Desert",
    duration: "5 Days",
    difficulty: "Moderate",
    difficultyStars: 3,
    tags: ["Sahara", "Desert", "Cultural", "Mountains"],
    cities: ["Tangier", "Chefchaouen", "Fes", "Merzouga", "Marrakech"],
    description: "Begin your adventure in the north with this 5-day Morocco tour from Tangier, designed for travelers who want to experience the country's rich diversity from the cool blue tones of Chefchaouen to the golden dunes of the Sahara Desert.",
    highlights: [
      "Blue-painted Chefchaouen",
      "Ancient Roman ruins",
      "Medieval medina of Fes",
      "Barbary macaques in cedar forests",
      "Sahara Desert camel trek",
      "Luxury desert camp experience",
      "Todra Gorge",
      "Dades Valley",
      "Ait Ben Haddou fortress"
    ],
    thumbnail: {
      src: "https://images.unsplash.com/photo-1489749798305-4fea3ba63d60?w=800&h=600&fit=crop",
      alt: "Blue streets of Chefchaouen",
      position: "object-center"
    },
    dayByDay: [
      { day: 1, title: "Tangier – Chefchaouen", description: "Travel through Rif Mountains to Chefchaouen. Explore the blue medina and Plaza Uta el Hammam." },
      { day: 2, title: "Chefchaouen – Volubilis – Meknes – Fes", description: "Visit Roman site Volubilis, explore imperial city Meknes, arrive in Fes for evening in the medina." },
      { day: 3, title: "Fes – Ifrane – Merzouga", description: "Drive through Middle Atlas Mountains, see Barbary macaques, descend into Ziz Valley. Camel trek into Erg Chebbi at sunset. Night in luxury desert camp." },
      { day: 4, title: "Merzouga – Todra Gorge – Dades Gorge", description: "Sunrise over dunes. Journey through desert plains to Todra Gorge. Continue to Dades Gorge with its dramatic red cliffs." },
      { day: 5, title: "Dades – Ait Ben Haddou – Marrakech", description: "Travel along Road of a Thousand Kasbahs, visit Kasbah Amridil, explore Ait Ben Haddou, cross High Atlas to Marrakech." },
    ],
  },
  {
    id: "14-days-casablanca-imperial-sahara",
    order: 3,
    title: "14 Days Morocco Tour from Casablanca",
    subtitle: "Imperial Cities, Sahara Desert, Mountains & Coast",
    duration: "14 Days",
    difficulty: "Moderate",
    difficultyStars: 2,
    tags: ["Imperial Cities", "Sahara", "Coastal", "Cultural", "Adventure"],
    cities: ["Casablanca", "Rabat", "Tangier", "Chefchaouen", "Fes", "Merzouga", "Marrakech", "Essaouira"],
    description: "This comprehensive 14-day tour starts in Casablanca, wandering through the history-lined streets of Rabat, the lively port of Tangier, and the picture-perfect blue alleys of Chefchaouen. Journey south through Volubilis, Meknes, and the cultural depths of Fes before crossing the Middle Atlas to reach the Sahara for a camel trek and a night in a desert camp.",
    highlights: [
      "Hassan II Mosque in Casablanca",
      "Rabat's Kasbah of the Udayas",
      "Cap Spartel and Hercules Cave",
      "Asilah's coastal charm",
      "Chefchaouen's blue medina",
      "Volubilis Roman ruins",
      "Fes el-Bali UNESCO medina",
      "Chouara Tannery",
      "Sahara Desert camp experience",
      "Nomadic Berber villages",
      "Khamlia Gnawa music",
      "Todra and Dades Gorges",
      "Ait Ben Haddou fortress",
      "Marrakech's Jemaa el-Fnaa",
      "Essaouira beach town"
    ],
    thumbnail: {
      src: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&h=600&fit=crop",
      alt: "Aerial view of Marrakech medina",
      position: "object-center"
    },
    dayByDay: [
      { day: 1, title: "Arrival in Casablanca", description: "Welcome to Morocco. Visit Hassan II Mosque and explore the Corniche." },
      { day: 2, title: "Casablanca – Rabat – Tangier", description: "Travel to Rabat, visit Hassan Tower and Kasbah of the Udayas. Continue to Tangier for evening exploration." },
      { day: 3, title: "Tangier – Cap Spartel – Asilah – Chefchaouen", description: "Visit Cap Spartel and Hercules Cave, explore Asilah's medina, arrive in Chefchaouen for evening." },
      { day: 4, title: "Full Day in Chefchaouen", description: "Explore the blue medina, visit Kasbah Museum, optional hike to Akchour Waterfalls, sunset from Spanish Mosque." },
      { day: 5, title: "Chefchaouen – Volubilis – Meknes – Fes", description: "Visit Roman ruins at Volubilis, explore imperial city Meknes, arrive in Fes." },
      { day: 6, title: "Full Day Guided Tour of Fes", description: "Explore Fes el-Bali medina, visit Bou Inania Madrasa, see Chouara Tannery, visit Al-Qarawiyyin Mosque and University." },
      { day: 7, title: "Fes – Ifrane – Merzouga", description: "Drive through Middle Atlas Mountains, see Barbary macaques, arrive in Merzouga for sunset camel trek and desert camp." },
      { day: 8, title: "Full Day in Sahara Desert", description: "Sunrise over dunes, visit nomadic Berber families, explore Khamlia village with Gnawa music, sunset camel trek." },
      { day: 9, title: "Merzouga – Rissani – Todra Gorge – Dades Gorge", description: "Visit Rissani's traditional souk, explore Todra Gorge, continue to Dades Gorge." },
      { day: 10, title: "Dades Gorge – Kasbah Amridil – Ait Ben Haddou – Marrakech", description: "Travel along Road of a Thousand Kasbahs, visit Kasbah Amridil, explore Ait Ben Haddou, cross High Atlas to Marrakech." },
      { day: 11, title: "Full Day Guided Tour of Marrakech", description: "Explore Jemaa el-Fnaa square, visit Koutoubia Mosque, Bahia Palace, Saadian Tombs, and traditional souks." },
      { day: 12, title: "Marrakech – Atlas Mountains – Essaouira", description: "Drive through Atlas Mountains, visit Argan oil cooperative, arrive in coastal town Essaouira." },
      { day: 13, title: "Full Day in Essaouira", description: "Explore medina, visit fish market, relax on Atlantic beaches, optional water activities." },
      { day: 14, title: "Essaouira – Marrakech – Departure", description: "Return to Marrakech or depart from Essaouira." },
    ],
  },
  {
    id: "5-days-casablanca-fes-sahara",
    order: 4,
    title: "5 Days Morocco Tour from Casablanca",
    subtitle: "Fes, Sahara Desert & Marrakech",
    duration: "5 Days",
    difficulty: "Moderate",
    difficultyStars: 3,
    tags: ["Sahara", "Desert", "Imperial Cities", "Cultural"],
    cities: ["Casablanca", "Fes", "Merzouga", "Marrakech"],
    description: "This 5-day tour brings together Morocco's most iconic landscapes and cultural highlights in one unforgettable journey. From the lively streets of Casablanca to the historic medina of Fes, the first days introduce you to Morocco's rich heritage. The adventure then heads south across the Middle Atlas Mountains toward the golden dunes of the Sahara Desert.",
    highlights: [
      "Hassan II Mosque",
      "Fes medina exploration",
      "Middle Atlas Mountains",
      "Cedar forests and Barbary macaques",
      "Ziz Valley palm groves",
      "Sahara Desert camel trek",
      "Luxury desert camp",
      "Todra Gorge",
      "Dades Valley",
      "Ait Ben Haddou",
      "High Atlas Mountains",
      "Marrakech's vibrant atmosphere"
    ],
    thumbnail: {
      src: "https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?w=800&h=600&fit=crop",
      alt: "Camel trekking in Sahara Desert",
      position: "object-center"
    },
    dayByDay: [
      { day: 1, title: "Arrival in Casablanca", description: "Welcome in Casablanca. Visit Hassan II Mosque and explore the Corniche before heading to Fes." },
      { day: 2, title: "Casablanca – Fes", description: "Travel through fertile plains to Fes, Morocco's spiritual capital. Check into traditional riad and explore the medina." },
      { day: 3, title: "Fes – Ifrane – Merzouga", description: "Drive south through Middle Atlas Mountains, see Barbary macaques in cedar forests, descend through Ziz Valley. Camel trek into Erg Chebbi at sunset. Night in luxury desert camp." },
      { day: 4, title: "Merzouga – Todra Gorge – Dades Gorge", description: "Sunrise over dunes. Journey west through desert landscapes to Todra Gorge. Continue to Dades Gorge with dramatic scenery." },
      { day: 5, title: "Dades – Ait Ben Haddou – Marrakech", description: "Travel along Road of a Thousand Kasbahs, visit Kasbah Amridil, explore Ait Ben Haddou, cross High Atlas to Marrakech." },
    ],
  },
  {
    id: "7-days-casablanca-rabat-fes-desert",
    order: 5,
    title: "7 Days in Morocco from Casablanca",
    subtitle: "Rabat, Fes, Desert & Marrakech",
    duration: "7 Days",
    difficulty: "Moderate",
    difficultyStars: 2,
    tags: ["Imperial Cities", "Sahara", "Desert", "Cultural"],
    cities: ["Casablanca", "Rabat", "Fes", "Merzouga", "Marrakech"],
    description: "7-day Morocco tour from Casablanca featuring Rabat, Chefchaouen, Fes, a Sahara Desert camel trek in Merzouga, Todra Gorge, and more.",
    highlights: [
      "Rabat's imperial architecture",
      "Chefchaouen's blue streets",
      "Fes medina",
      "Middle Atlas Mountains",
      "Sahara Desert experience",
      "Camel trekking",
      "Todra Gorge",
      "Dades Valley",
      "Marrakech exploration"
    ],
    thumbnail: {
      src: "https://images.unsplash.com/photo-1488646953014-85cb44e25828?w=800&h=600&fit=crop",
      alt: "Majestic Atlas Mountains landscape",
      position: "object-center"
    },
    dayByDay: [
      { day: 1, title: "Casablanca – Rabat", description: "Explore Casablanca, travel to Rabat, visit Hassan Tower and Kasbah." },
      { day: 2, title: "Rabat – Chefchaouen", description: "Travel to Chefchaouen, explore the blue medina." },
      { day: 3, title: "Chefchaouen – Fes", description: "Journey to Fes, explore the historic medina." },
      { day: 4, title: "Fes – Merzouga", description: "Drive through Middle Atlas to Merzouga. Camel trek and desert camp night." },
      { day: 5, title: "Merzouga – Todra Gorge", description: "Explore desert, travel to Todra Gorge." },
      { day: 6, title: "Todra – Dades – Ait Ben Haddou", description: "Visit Dades Gorge, explore Ait Ben Haddou." },
      { day: 7, title: "Ait Ben Haddou – Marrakech", description: "Cross High Atlas Mountains, arrive in Marrakech." },
    ],
  },
  {
    id: "2-days-errachidia-fes-desert",
    order: 6,
    title: "2 Days Errachidia to Fes Desert Tour",
    subtitle: "Sahara & Middle Atlas Journey",
    duration: "2 Days",
    difficulty: "Easy",
    difficultyStars: 2,
    tags: ["Desert", "Mountains", "Short Break"],
    cities: ["Errachidia", "Merzouga", "Fes"],
    description: "2-day Fes to Merzouga Desert Tour through the Middle Atlas Mountains and Ziz Valley with a camel trek and overnight stay in the desert.",
    highlights: [
      "Middle Atlas Mountains",
      "Ziz Valley",
      "Sahara Desert",
      "Camel trek",
      "Desert camp experience"
    ],
    thumbnail: {
      src: getStaticImageUrl("/hero-sahara-sunset.png"),
      alt: "Desert landscape",
      position: "object-center"
    },
    dayByDay: [
      { day: 1, title: "Errachidia – Merzouga", description: "Travel through Middle Atlas Mountains and Ziz Valley. Camel trek into Erg Chebbi at sunset. Night in desert camp." },
      { day: 2, title: "Merzouga – Fes", description: "Sunrise over dunes. Return journey to Fes." },
    ],
  },
  {
    id: "4-days-errachidia-marrakech-desert",
    order: 7,
    title: "4 Days Errachidia to Marrakech Desert Tour",
    subtitle: "Sahara, Kasbahs & Atlas Mountains",
    duration: "4 Days",
    difficulty: "Moderate",
    difficultyStars: 3,
    tags: ["Desert", "Kasbahs", "Mountains", "Cultural"],
    cities: ["Errachidia", "Merzouga", "Marrakech"],
    description: "4-day tour from Errachidia to Marrakech exploring the Sahara Desert, ancient kasbahs, and the High Atlas Mountains.",
    highlights: [
      "Sahara Desert",
      "Camel trekking",
      "Desert camp",
      "Ancient kasbahs",
      "Todra Gorge",
      "High Atlas Mountains"
    ],
    thumbnail: {
      src: getStaticImageUrl("/hero-atlas-mountains.png"),
      alt: "Mountain landscape",
      position: "object-center"
    },
    dayByDay: [
      { day: 1, title: "Errachidia – Merzouga", description: "Travel to Merzouga. Camel trek into Erg Chebbi. Desert camp night." },
      { day: 2, title: "Merzouga – Todra Gorge", description: "Explore desert, travel to Todra Gorge." },
      { day: 3, title: "Todra – Dades – Ait Ben Haddou", description: "Visit Dades Gorge, explore Ait Ben Haddou." },
      { day: 4, title: "Ait Ben Haddou – Marrakech", description: "Cross High Atlas Mountains to Marrakech." },
    ],
  },
  {
    id: "3-days-errachidia-merzouga",
    order: 8,
    title: "3 Days Errachidia to Merzouga Desert Tour",
    subtitle: "Sahara & Erg Chebbi Experience",
    duration: "3 Days",
    difficulty: "Easy",
    difficultyStars: 2,
    tags: ["Desert", "Sahara", "Camel Trek"],
    cities: ["Errachidia", "Merzouga"],
    description: "3-day Errachidia to Merzouga Desert Tour exploring the Sahara and Erg Chebbi dunes with camel trekking and desert camp experience.",
    highlights: [
      "Sahara Desert",
      "Erg Chebbi dunes",
      "Camel trekking",
      "Desert camp",
      "Berber culture"
    ],
    thumbnail: {
      src: getStaticImageUrl("/hero-sahara-sunset.png"),
      alt: "Sahara dunes",
      position: "object-center"
    },
    dayByDay: [
      { day: 1, title: "Errachidia – Merzouga", description: "Travel to Merzouga. Camel trek into Erg Chebbi at sunset. Night in luxury desert camp." },
      { day: 2, title: "Merzouga Exploration", description: "Sunrise over dunes. Explore desert landscapes and Berber culture." },
      { day: 3, title: "Merzouga – Return", description: "Final morning in the desert before departure." },
    ],
  },
  {
    id: "4-days-marrakech-fes-desert",
    order: 9,
    title: "4 Days Marrakech to Fes Desert Tour",
    subtitle: "2 Nights Sahara",
    duration: "4 Days",
    difficulty: "Moderate",
    difficultyStars: 3,
    tags: ["Desert", "Sahara", "Imperial Cities"],
    cities: ["Marrakech", "Merzouga", "Fes"],
    description: "Experience the Sahara in 4 days from Marrakech to Fes with 2 nights in the desert, camel trekking, and unforgettable landscapes.",
    highlights: [
      "Marrakech medina",
      "High Atlas Mountains",
      "Sahara Desert",
      "Camel trekking",
      "Desert camp experience",
      "Todra Gorge",
      "Fes medina"
    ],
    thumbnail: {
      src: getStaticImageUrl("/hero-camel-trek.png"),
      alt: "Desert adventure",
      position: "object-center"
    },
    dayByDay: [
      { day: 1, title: "Marrakech – High Atlas – Merzouga", description: "Leave Marrakech, cross High Atlas Mountains, arrive in Merzouga. Camel trek into Erg Chebbi at sunset. Desert camp night." },
      { day: 2, title: "Sahara Exploration", description: "Sunrise over dunes. Explore desert landscapes and Berber villages. Second night in desert." },
      { day: 3, title: "Merzouga – Todra Gorge", description: "Journey west to Todra Gorge with dramatic limestone cliffs." },
      { day: 4, title: "Todra – Fes", description: "Travel to Fes, arriving in the historic imperial city." },
    ],
  },
  {
    id: "3-days-marrakech-fes-desert",
    order: 10,
    title: "3 Days Marrakech to Fes Desert Tour",
    subtitle: "Sahara & Erg Chebbi",
    duration: "3 Days",
    difficulty: "Moderate",
    difficultyStars: 3,
    tags: ["Desert", "Sahara", "Quick Trip"],
    cities: ["Marrakech", "Merzouga", "Fes"],
    description: "3-day desert tour from Marrakech to Fes with Sahara camel trekking and overnight stay in the desert.",
    highlights: [
      "High Atlas Mountains",
      "Sahara Desert",
      "Erg Chebbi dunes",
      "Camel trekking",
      "Desert camp",
      "Todra Gorge",
      "Fes medina"
    ],
    thumbnail: {
      src: getStaticImageUrl("/hero-blue-chefchaouen.png"),
      alt: "Morocco landscape",
      position: "object-center"
    },
    dayByDay: [
      { day: 1, title: "Marrakech – Merzouga", description: "Cross High Atlas Mountains to Merzouga. Camel trek into Erg Chebbi at sunset. Desert camp night." },
      { day: 2, title: "Merzouga – Todra Gorge", description: "Sunrise over dunes. Journey to Todra Gorge." },
      { day: 3, title: "Todra – Fes", description: "Travel to Fes, arriving in the imperial city." },
    ],
  },
];
